Update vast.py
When show__instance is called immediately after an instance is created, the API endpoint /api/v0/instances/{id}/ may return a JSON object where the value for the "instances" key is null. The existing code does not handle this case, leading to the row variable being None, which causes a TypeError when the code attempts to access row['start_date'].

Traceback:

File ".../vast.py", line 3750, in show__instance
  row['duration'] = time.time() - row['start_date']
TypeError: 'NoneType' object is not subscriptable